
-- 10 SÁCH MẪU cho Tủ sách (danh sách tham khảo: Fahasa – Top 10 sách self-help). Nội dung Trước/Sau và trích dẫn là [MẪU]
INSERT INTO reflections (kind, slug, title, author, color, before_text, after_text, quotes, lessons, question, status, published_at, sort, visible, created_at, updated_at)
VALUES ('book', 'mau-s-7-thoi-quen', '7 Thói Quen Hiệu Quả', 'Stephen R. Covey', '#2F4F6B', '[MẪU] Chỗ này anh ghi: trước khi đọc, anh từng nghĩ thế nào về chủ đề của cuốn sách.', '[MẪU] Chỗ này anh ghi: sau khi đọc, anh đã nghĩ khác và làm khác điều gì.', '[MẪU] Câu anh gạch chân trong sách (chép nguyên văn, ngắn) | tr. ...', 'Bắt đầu với mục tiêu trong đầu; ưu tiên việc quan trọng trước việc khẩn cấp
Tư duy cùng thắng thay vì thắng – thua
Lắng nghe để hiểu trước khi muốn được hiểu', 'Tuần này, việc quan trọng nhưng không khẩn cấp nào bạn lại để lùi?', 'published', '2026-10-07', 20, 1, strftime('%s','now')*1000, strftime('%s','now')*1000)
ON CONFLICT(slug) DO UPDATE SET title=excluded.title, author=excluded.author, color=excluded.color, before_text=excluded.before_text, after_text=excluded.after_text, quotes=excluded.quotes, lessons=excluded.lessons, question=excluded.question, status=excluded.status, sort=excluded.sort, updated_at=excluded.updated_at;
INSERT INTO reflections (kind, slug, title, author, color, before_text, after_text, quotes, lessons, question, status, published_at, sort, visible, created_at, updated_at)
VALUES ('book', 'mau-s-nha-gia-kim', 'Nhà Giả Kim', 'Paulo Coelho', '#B0743A', '[MẪU] Chỗ này anh ghi: trước khi đọc, anh từng nghĩ thế nào về chủ đề của cuốn sách.', '[MẪU] Chỗ này anh ghi: sau khi đọc, anh đã nghĩ khác và làm khác điều gì.', '[MẪU] Câu anh gạch chân trong sách (chép nguyên văn, ngắn) | tr. ...', 'Theo đuổi điều mình thật sự muốn là một hành trình, không phải một đích đến
Những trở ngại trên đường cũng là một phần của bài học', 'Ước mơ nào bạn đã cất đi vì "chưa phải lúc"?', 'published', '2026-10-07', 21, 1, strftime('%s','now')*1000, strftime('%s','now')*1000)
ON CONFLICT(slug) DO UPDATE SET title=excluded.title, author=excluded.author, color=excluded.color, before_text=excluded.before_text, after_text=excluded.after_text, quotes=excluded.quotes, lessons=excluded.lessons, question=excluded.question, status=excluded.status, sort=excluded.sort, updated_at=excluded.updated_at;
INSERT INTO reflections (kind, slug, title, author, color, before_text, after_text, quotes, lessons, question, status, published_at, sort, visible, created_at, updated_at)
VALUES ('book', 'mau-s-tu-duy-nhanh-cham', 'Tư Duy Nhanh Và Chậm', 'Daniel Kahneman', '#3D6E6A', '[MẪU] Chỗ này anh ghi: trước khi đọc, anh từng nghĩ thế nào về chủ đề của cuốn sách.', '[MẪU] Chỗ này anh ghi: sau khi đọc, anh đã nghĩ khác và làm khác điều gì.', '[MẪU] Câu anh gạch chân trong sách (chép nguyên văn, ngắn) | tr. ...', 'Bộ não có hai hệ thống: nhanh – trực giác và chậm – cân nhắc
Nhiều quyết định sai đến từ lối tắt của tư duy nhanh
Quyết định quan trọng cần được làm chậm lại có chủ đích', 'Quyết định gần nhất bạn làm "theo cảm giác" là gì – nếu làm chậm lại, kết quả có khác?', 'published', '2026-10-07', 22, 1, strftime('%s','now')*1000, strftime('%s','now')*1000)
ON CONFLICT(slug) DO UPDATE SET title=excluded.title, author=excluded.author, color=excluded.color, before_text=excluded.before_text, after_text=excluded.after_text, quotes=excluded.quotes, lessons=excluded.lessons, question=excluded.question, status=excluded.status, sort=excluded.sort, updated_at=excluded.updated_at;
INSERT INTO reflections (kind, slug, title, author, color, before_text, after_text, quotes, lessons, question, status, published_at, sort, visible, created_at, updated_at)
VALUES ('book', 'mau-s-dam-bi-ghet', 'Dám Bị Ghét', 'Kishimi Ichiro & Koga Fumitake', '#7A3B4B', '[MẪU] Chỗ này anh ghi: trước khi đọc, anh từng nghĩ thế nào về chủ đề của cuốn sách.', '[MẪU] Chỗ này anh ghi: sau khi đọc, anh đã nghĩ khác và làm khác điều gì.', '[MẪU] Câu anh gạch chân trong sách (chép nguyên văn, ngắn) | tr. ...', 'Tách bạch việc của mình và việc của người khác
Sống theo kỳ vọng của người khác khiến ta mất tự do
Hạnh phúc đến từ cảm giác đóng góp', 'Bạn đang gánh "việc của người khác" nào mà không cần thiết?', 'published', '2026-10-07', 23, 1, strftime('%s','now')*1000, strftime('%s','now')*1000)
ON CONFLICT(slug) DO UPDATE SET title=excluded.title, author=excluded.author, color=excluded.color, before_text=excluded.before_text, after_text=excluded.after_text, quotes=excluded.quotes, lessons=excluded.lessons, question=excluded.question, status=excluded.status, sort=excluded.sort, updated_at=excluded.updated_at;
INSERT INTO reflections (kind, slug, title, author, color, before_text, after_text, quotes, lessons, question, status, published_at, sort, visible, created_at, updated_at)
VALUES ('book', 'mau-s-nguoi-giau-babylon', 'Người Giàu Nhất Thành Babylon', 'George S. Clason', '#C9A15A', '[MẪU] Chỗ này anh ghi: trước khi đọc, anh từng nghĩ thế nào về chủ đề của cuốn sách.', '[MẪU] Chỗ này anh ghi: sau khi đọc, anh đã nghĩ khác và làm khác điều gì.', '[MẪU] Câu anh gạch chân trong sách (chép nguyên văn, ngắn) | tr. ...', 'Trả cho mình trước: để dành một phần thu nhập đều đặn
Để đồng tiền làm việc cho mình
Học hỏi từ người có kinh nghiệm trước khi đầu tư', 'Tháng này bạn đã "trả cho mình trước" bao nhiêu phần trăm thu nhập?', 'published', '2026-10-07', 24, 1, strftime('%s','now')*1000, strftime('%s','now')*1000)
ON CONFLICT(slug) DO UPDATE SET title=excluded.title, author=excluded.author, color=excluded.color, before_text=excluded.before_text, after_text=excluded.after_text, quotes=excluded.quotes, lessons=excluded.lessons, question=excluded.question, status=excluded.status, sort=excluded.sort, updated_at=excluded.updated_at;
INSERT INTO reflections (kind, slug, title, author, color, before_text, after_text, quotes, lessons, question, status, published_at, sort, visible, created_at, updated_at)
VALUES ('book', 'mau-s-nghi-giau-lam-giau', 'Nghĩ Giàu Làm Giàu', 'Napoleon Hill', '#5B6B3A', '[MẪU] Chỗ này anh ghi: trước khi đọc, anh từng nghĩ thế nào về chủ đề của cuốn sách.', '[MẪU] Chỗ này anh ghi: sau khi đọc, anh đã nghĩ khác và làm khác điều gì.', '[MẪU] Câu anh gạch chân trong sách (chép nguyên văn, ngắn) | tr. ...', 'Mong muốn rõ ràng là điểm khởi đầu của thành tựu
Kiên trì và kế hoạch cụ thể biến mong muốn thành hiện thực
Nhóm cộng sự cùng chí hướng nhân sức mạnh lên', 'Mục tiêu năm nay của bạn đã được viết ra thành kế hoạch cụ thể chưa?', 'published', '2026-10-07', 25, 1, strftime('%s','now')*1000, strftime('%s','now')*1000)
ON CONFLICT(slug) DO UPDATE SET title=excluded.title, author=excluded.author, color=excluded.color, before_text=excluded.before_text, after_text=excluded.after_text, quotes=excluded.quotes, lessons=excluded.lessons, question=excluded.question, status=excluded.status, sort=excluded.sort, updated_at=excluded.updated_at;
INSERT INTO reflections (kind, slug, title, author, color, before_text, after_text, quotes, lessons, question, status, published_at, sort, visible, created_at, updated_at)
VALUES ('book', 'mau-s-atomic-habits', 'Atomic Habits', 'James Clear', '#8E3B2F', '[MẪU] Chỗ này anh ghi: trước khi đọc, anh từng nghĩ thế nào về chủ đề của cuốn sách.', '[MẪU] Chỗ này anh ghi: sau khi đọc, anh đã nghĩ khác và làm khác điều gì.', '[MẪU] Câu anh gạch chân trong sách (chép nguyên văn, ngắn) | tr. ...', 'Thay đổi nhỏ 1% mỗi ngày cộng dồn thành khác biệt lớn
Thiết kế môi trường để thói quen tốt dễ làm hơn
Gắn thói quen với bản sắc: "tôi là người…"', 'Thói quen nhỏ nào bạn có thể bắt đầu ngay hôm nay trong 2 phút?', 'published', '2026-10-07', 26, 1, strftime('%s','now')*1000, strftime('%s','now')*1000)
ON CONFLICT(slug) DO UPDATE SET title=excluded.title, author=excluded.author, color=excluded.color, before_text=excluded.before_text, after_text=excluded.after_text, quotes=excluded.quotes, lessons=excluded.lessons, question=excluded.question, status=excluded.status, sort=excluded.sort, updated_at=excluded.updated_at;
INSERT INTO reflections (kind, slug, title, author, color, before_text, after_text, quotes, lessons, question, status, published_at, sort, visible, created_at, updated_at)
VALUES ('book', 'mau-s-cha-giau-cha-ngheo', 'Cha Giàu, Cha Nghèo', 'Robert T. Kiyosaki & Sharon L. Lechter', '#6E4A86', '[MẪU] Chỗ này anh ghi: trước khi đọc, anh từng nghĩ thế nào về chủ đề của cuốn sách.', '[MẪU] Chỗ này anh ghi: sau khi đọc, anh đã nghĩ khác và làm khác điều gì.', '[MẪU] Câu anh gạch chân trong sách (chép nguyên văn, ngắn) | tr. ...', 'Phân biệt tài sản và tiêu sản
Học về tài chính quan trọng không kém học để đi làm
Để tiền làm việc cho mình thay vì chỉ làm việc vì tiền', 'Thứ bạn đang gọi là "tài sản" có thật sự mang tiền về cho bạn không?', 'published', '2026-10-07', 27, 1, strftime('%s','now')*1000, strftime('%s','now')*1000)
ON CONFLICT(slug) DO UPDATE SET title=excluded.title, author=excluded.author, color=excluded.color, before_text=excluded.before_text, after_text=excluded.after_text, quotes=excluded.quotes, lessons=excluded.lessons, question=excluded.question, status=excluded.status, sort=excluded.sort, updated_at=excluded.updated_at;
INSERT INTO reflections (kind, slug, title, author, color, before_text, after_text, quotes, lessons, question, status, published_at, sort, visible, created_at, updated_at)
VALUES ('book', 'mau-s-minh-la-ca', 'Mình Là Cá, Việc Của Mình Là Bơi', 'Takeshi Furukawa', '#2E3A55', '[MẪU] Chỗ này anh ghi: trước khi đọc, anh từng nghĩ thế nào về chủ đề của cuốn sách.', '[MẪU] Chỗ này anh ghi: sau khi đọc, anh đã nghĩ khác và làm khác điều gì.', '[MẪU] Câu anh gạch chân trong sách (chép nguyên văn, ngắn) | tr. ...', 'Chấp nhận bản thân là bước đầu để sống vui
Bớt so sánh với người khác
Những thói quen nhỏ giúp vượt qua suy nghĩ tiêu cực', 'Bạn đang cố "trèo cây" ở việc gì, trong khi điểm mạnh của bạn là "bơi"?', 'published', '2026-10-07', 28, 1, strftime('%s','now')*1000, strftime('%s','now')*1000)
ON CONFLICT(slug) DO UPDATE SET title=excluded.title, author=excluded.author, color=excluded.color, before_text=excluded.before_text, after_text=excluded.after_text, quotes=excluded.quotes, lessons=excluded.lessons, question=excluded.question, status=excluded.status, sort=excluded.sort, updated_at=excluded.updated_at;
INSERT INTO reflections (kind, slug, title, author, color, before_text, after_text, quotes, lessons, question, status, published_at, sort, visible, created_at, updated_at)
VALUES ('book', 'mau-s-doi-ngan-dung-ngu-dai', 'Đời Ngắn Đừng Ngủ Dài', 'Robin Sharma', '#B44A35', '[MẪU] Chỗ này anh ghi: trước khi đọc, anh từng nghĩ thế nào về chủ đề của cuốn sách.', '[MẪU] Chỗ này anh ghi: sau khi đọc, anh đã nghĩ khác và làm khác điều gì.', '[MẪU] Câu anh gạch chân trong sách (chép nguyên văn, ngắn) | tr. ...', 'Thời gian là tài sản quý nhất, đừng trì hoãn điều quan trọng
Sống có mục đích và theo đuổi đam mê
Mỗi ngày là cơ hội để làm tốt hơn hôm qua', 'Nếu chỉ còn một năm, bạn sẽ ngừng làm điều gì ngay?', 'published', '2026-10-07', 29, 1, strftime('%s','now')*1000, strftime('%s','now')*1000)
ON CONFLICT(slug) DO UPDATE SET title=excluded.title, author=excluded.author, color=excluded.color, before_text=excluded.before_text, after_text=excluded.after_text, quotes=excluded.quotes, lessons=excluded.lessons, question=excluded.question, status=excluded.status, sort=excluded.sort, updated_at=excluded.updated_at;
